### ISSUE TITLE
minikube cluster error

### ISSUE THREAD

**Issue by prajakta2055** [candiceT233/Kubernetes-Dynamic-Volume#2]
I created a minikube single node cluster and worked on it. But after I shut down the machine and restart later to work on, minikube gives below error:

pk@pk-virtual-machine:~$ kubectl get po -A
E0324 09:03:45.972726    2807 memcache.go:238] couldn't get current server API group list: Get "https://192.168.49.2:8443/api?timeout=32s": dial tcp 192.168.49.2:8443: connect: no route to host

**Comment by prajakta2055** [comment]
everytime I have to delete and create the cluster using:

minikube delete && minikube start

**Comment by candiceT233** [comment]
> 

It seems to me `minikube delete` is actually deleting the cluster. If you want to keep the cluster for future work, you should use `minikube pause`.
Here is a reference to the minikube commands: https://minikube.sigs.k8s.io/docs/commands/

**Comment by AmithGspn** [comment]
We have tried the above solution given by you. But still the error remains the same,

**Comment by AmithGspn** [comment]
Fixed the issue

The command "mnikube start" threw the following error 
"Exiting due to PROVIDER_DOCKER_NEWGRP: "docker version --format -:" exit status 1: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied"

Fixed the above problem as mentioned below
Firstly, Added user to docker group by using the following command
"sudo usermod -aG docker $USER && newgrp docker"

Then ran "minikube start" and things worked as expected.

Everytime the systems is rebooted we need to do "minikube start" inorder  to restart all the existing docker instances.
